<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => 'Aktivní',
    'Auth Key' => 'Autorizační klíč',
    'Category ID' => '# Kategorie',
    'Code' => 'Kód',
    'Component' => 'Komponenta',
    'Computed by Weight' => 'Počítáno dle váhy',
    'Created At' => 'Vytvořeno',
    'Description' => 'Popis',
    'Discount Price' => 'Sleva',
    'Email' => 'Email',
    'End Date' => 'Koncové datum',
    'First Name' => 'Jméno',
    'Flat' => 'Striktní přirážka',
    'ID' => '#',
    'Inserted At' => 'Vytvořeno',
    'Last Name' => 'Příjmení',
    'Link Active' => 'Aktivní odkaz',
    'Multiple' => 'Vícenásobné',
    'Name' => 'Jméno',
    'Parent ID' => 'Nadřazená položka',
    'Password Hash' => 'Šifrované heslo',
    'Password Reset Token' => 'Klíč pro reset hesla',
    'Price' => 'Cena',
    'Product ID' => 'Číslo produktu',
    'Product Status ID' => 'Stav produktu',
    'Quantity' => 'Kvantita',
    'Query' => 'Dotaz',
    'Regular Price' => 'Cena',
    'Role ID' => 'Číslo role',
    'Shippin ID' => 'Číslo poštovného',
    'Shipping Type' => 'Typ poštovného',
    'Sku' => 'SKU',
    'Slug' => 'Url adresa',
    'Start Date' => 'Datum začátku',
    'Status' => 'Stav',
    'Subtitle' => 'Podtitulek',
    'Tag ID' => 'Číslo štítku',
    'Taxable' => 'Danitelné',
    'Text' => 'Obsah',
    'Title' => 'Titulek',
    'Updated At' => 'Upraveno',
    'User ID' => 'Číslo uživatele',
    'Value' => 'hodnota',
    'Weight' => 'váha',
    'Write atleast 3 symbols' => 'Napište alespoň 3 znaky',
];
